### ISSUE TITLE
schematics: publish script throws an error in terminal

### ISSUE THREAD

**Issue by brunobuddy** [casejs/CASE#64]
When running `npm run publish` for schematics, the terminal throws an error at the end of the script.

The package **still gets published as intended** which is ambiguous 

```bash
> @casejs/schematics@2.0.5 move
> rm -rf dist && mkdir -p dist/commands/create-entity/files && cp -aR ./src/commands/create-entity/files/* dist/commands/create-entity/files

cp: cannot stat './src/commands/create-entity/files/*': No such file or directory
npm ERR! code 1
npm ERR! path /home/brunobuddy/Codebases/case-app/case/packages/schematics/dist
npm ERR! command failed
npm ERR! command sh -c npm run build && cd dist && npm publish

npm ERR! A complete log of this run can be found in: /home/brunobuddy/.npm/_logs/2023-09-17T17_40_06_732Z-debug-0.log
npm ERR! Lifecycle script `publish` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @casejs/schematics@2.0.5 
npm ERR!   at location: /home/brunobuddy/Codebases/case-app/case/packages/schematics 
```

**Comment by shavidze** [comment]
I can't reproduce this kind of error, 
But what I can is this, since the version 2.0.5 has already published and I don't have a permission to publish it


```js
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@casejs%2fschematics - Not found
npm ERR! 404 
npm ERR! 404  '@casejs/schematics@2.0.5' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/sabashavidze/.npm/_logs/2023-10-04T12_44_31_167Z-debug-0.log
npm ERR! Lifecycle script `publish` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @casejs/schematics@2.0.5 
npm ERR!   at location: /Users/sabashavidze/Projects/CASE/packages/schematics 
```

I'd like to propose a more streamlined and automated solution using `Github Actions` and [`semantic-release`](https://semantic-release.gitbook.io/), which based on pushing on the master branch, will use our commit message to determine the type of version bump: `major`, `minor`, `patch`.

## semantic-release configuration file would look like: 

```js
module.exports = {
  // Specify the branches that can trigger a release
  branches: ['master'],

  plugins: [
    // Analyze commit messages to determine the type of version bump
    '@semantic-release/commit-analyzer',

    // Generate release notes based on commit messages
    '@semantic-release/release-notes-generator',

    // Create or update a CHANGELOG.md file
    '@semantic-release/changelog',

    // Publish the release to npm
    ['@semantic-release/npm', {
      // If set to true, the module will be published to npm
      npmPublish: true,

      // Directory where the tarball package file should be written
      // If you don't need to save the tarball, you can remove this option
      tarballDir: 'dist'
    }],

    // Create a new release on GitHub
    '@semantic-release/github'
  ]
};


```

## Github Action


```yaml
name: CI/CD for @casejs/schematics

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Change to dist directory
      run: cd packages/schematics/dist

    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
